<#-- Terraform AWS Configuration — generated by InfraForge -->
<#assign s = sections>
<#assign p = s.provider.instances[0]>
<#-- Helper: format a comma-separated string as an HCL list -->
<#-- Usage: <@hclList value=myField /> -->
<#macro hclList value>[<#list value?split(",") as item><#if item?trim?has_content>"${item?trim}"<#sep>, </#sep></#if></#list>]</#macro>
<#-- Helper: format textarea (one item per line) as HCL list -->
<#macro hclLines value>[<#list value?split("\n") as item><#if item?trim?has_content>"${item?trim}"<#sep>, </#sep></#if></#list>]</#macro>

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
<#if s.backend?? && s.backend.enabled>
<#assign b = s.backend.instances[0]>

  backend "${b.backend_type}" {
<#if b.backend_type == "s3">
    bucket = "${b.s3_bucket}"
    key    = "${b.s3_key}"
    region = "${b.s3_region}"
<#if b.dynamodb_table?has_content>
    dynamodb_table = "${b.dynamodb_table}"
</#if>
    encrypt = ${b.encrypt!"true"}
<#elseif b.backend_type == "remote">
    hostname     = "app.terraform.io"
    organization = "YOUR_ORG"
    workspaces {
      name = "YOUR_WORKSPACE"
    }
<#else>
    path = "terraform.tfstate"
</#if>
  }
</#if>
}

provider "aws" {
  region = "${p.region}"
<#if p.credentials_method == "shared_credentials_file">
  profile = "${p.profile_name!"default"}"
<#elseif p.credentials_method == "static_keys">
  access_key = "${p.access_key}"
  secret_key = "${p.secret_key}"
</#if>
}
<#-- ============================================================ -->
<#-- VPC                                                          -->
<#-- ============================================================ -->
<#if s.vpc?? && s.vpc.enabled>
<#assign vpc = s.vpc.instances[0]>

resource "aws_vpc" "${vpc.resource_name!"main"}" {
  cidr_block           = "${vpc.cidr_block}"
  enable_dns_support   = ${vpc.enable_dns_support!"true"}
  enable_dns_hostnames = ${vpc.enable_dns_hostnames!"true"}
  instance_tenancy     = "${vpc.instance_tenancy!"default"}"
<#if vpc.name_tag?has_content || vpc.environment_tag?has_content>

  tags = {
<#if vpc.name_tag?has_content>
    Name        = "${vpc.name_tag}"
</#if>
<#if vpc.environment_tag?has_content>
    Environment = "${vpc.environment_tag}"
</#if>
  }
</#if>
}
</#if>
<#-- ============================================================ -->
<#-- Internet Gateway                                             -->
<#-- ============================================================ -->
<#if s.internet_gateway?? && s.internet_gateway.enabled>
<#assign igw = s.internet_gateway.instances[0]>

resource "aws_internet_gateway" "${igw.resource_name!"main"}" {
  vpc_id = aws_vpc.${igw.vpc_ref!"main"}.id
<#if igw.name_tag?has_content>

  tags = {
    Name = "${igw.name_tag}"
  }
</#if>
}
</#if>
<#-- ============================================================ -->
<#-- Subnets                                                      -->
<#-- ============================================================ -->
<#if s.subnet?? && s.subnet.enabled>
<#list s.subnet.instances as subnet>

resource "aws_subnet" "${subnet.resource_name!("subnet_" + (subnet?index + 1))}" {
  vpc_id                  = aws_vpc.${subnet.vpc_ref!"main"}.id
  cidr_block              = "${subnet.cidr_block}"
  availability_zone       = "${subnet.availability_zone}"
  map_public_ip_on_launch = ${subnet.map_public_ip_on_launch!"false"}
<#if subnet.name_tag?has_content>

  tags = {
    Name = "${subnet.name_tag}"
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- Security Groups                                              -->
<#-- ============================================================ -->
<#if s.security_group?? && s.security_group.enabled>
<#list s.security_group.instances as sg>

resource "aws_security_group" "${sg.resource_name!("sg_" + (sg?index + 1))}" {
  name        = "${sg.name}"
  description = "${sg.description!"Managed by InfraForge"}"
<#if sg.vpc_ref?has_content>
  vpc_id      = aws_vpc.${sg.vpc_ref}.id
</#if>
<#if sg.ingress_from_port?has_content>

  ingress {
    from_port   = ${sg.ingress_from_port}
    to_port     = ${sg.ingress_to_port!sg.ingress_from_port}
    protocol    = "${sg.ingress_protocol!"tcp"}"
    cidr_blocks = ["${sg.ingress_cidr!"0.0.0.0/0"}"]
  }
</#if>

  egress {
    from_port   = ${sg.egress_from_port!"0"}
    to_port     = ${sg.egress_to_port!"0"}
    protocol    = "${sg.egress_protocol!"-1"}"
    cidr_blocks = ["${sg.egress_cidr!"0.0.0.0/0"}"]
  }
<#if sg.name_tag?has_content>

  tags = {
    Name = "${sg.name_tag}"
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- Key Pair                                                     -->
<#-- ============================================================ -->
<#if s.key_pair?? && s.key_pair.enabled>
<#assign kp = s.key_pair.instances[0]>

resource "aws_key_pair" "${kp.resource_name!"deployer"}" {
  key_name   = "${kp.key_name}"
  public_key = "${kp.public_key}"
}
</#if>
<#-- ============================================================ -->
<#-- EC2 Instances                                                -->
<#-- ============================================================ -->
<#if s.ec2?? && s.ec2.enabled>
<#list s.ec2.instances as ec2>

resource "aws_instance" "${ec2.resource_name!("instance_" + (ec2?index + 1))}" {
  ami           = "${ec2.ami_id}"
  instance_type = "${ec2.instance_type!"t3.micro"}"
<#if ec2.key_name?has_content>
  key_name      = "${ec2.key_name}"
</#if>
<#if ec2.subnet_ref?has_content>
  subnet_id     = aws_subnet.${ec2.subnet_ref}.id
</#if>
<#if ec2.vpc_security_group_refs?has_content>
  vpc_security_group_ids = [<#list ec2.vpc_security_group_refs?split(",") as ref><#if ref?trim?has_content>aws_security_group.${ref?trim}.id<#sep>, </#sep></#if></#list>]
</#if>
  associate_public_ip_address = ${ec2.associate_public_ip!"false"}
<#if ec2.iam_instance_profile?has_content>
  iam_instance_profile        = "${ec2.iam_instance_profile}"
</#if>
  ebs_optimized = ${ec2.ebs_optimized!"true"}
  monitoring    = ${ec2.monitoring!"false"}

  root_block_device {
    volume_type           = "${ec2.root_volume_type!"gp3"}"
    volume_size           = ${ec2.root_volume_size!"20"}
    delete_on_termination = true
  }
<#if ec2.user_data?has_content>

  user_data = <<-EOF
${ec2.user_data}
  EOF
</#if>
<#if ec2.name_tag?has_content || ec2.environment_tag?has_content>

  tags = {
<#if ec2.name_tag?has_content>
    Name        = "${ec2.name_tag}"
</#if>
<#if ec2.environment_tag?has_content>
    Environment = "${ec2.environment_tag}"
</#if>
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- Elastic IPs                                                  -->
<#-- ============================================================ -->
<#if s.elastic_ip?? && s.elastic_ip.enabled>
<#list s.elastic_ip.instances as eip>

resource "aws_eip" "${eip.resource_name!("eip_" + (eip?index + 1))}" {
  domain = "vpc"
<#if eip.instance_ref?has_content>
  instance = aws_instance.${eip.instance_ref}.id
</#if>
<#if eip.name_tag?has_content>

  tags = {
    Name = "${eip.name_tag}"
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- S3 Buckets                                                   -->
<#-- ============================================================ -->
<#if s.s3?? && s.s3.enabled>
<#list s.s3.instances as bucket>

resource "aws_s3_bucket" "${bucket.resource_name!("bucket_" + (bucket?index + 1))}" {
  bucket        = "${bucket.bucket_name}"
  force_destroy = ${bucket.force_destroy!"false"}
<#if bucket.name_tag?has_content>

  tags = {
    Name = "${bucket.name_tag}"
  }
</#if>
}
<#if bucket.versioning_enabled?has_content && bucket.versioning_enabled == "true">

resource "aws_s3_bucket_versioning" "${bucket.resource_name!("bucket_" + (bucket?index + 1))}_versioning" {
  bucket = aws_s3_bucket.${bucket.resource_name!("bucket_" + (bucket?index + 1))}.id

  versioning_configuration {
    status = "Enabled"
  }
}
</#if>
<#if bucket.sse_algorithm?has_content && bucket.sse_algorithm != "none">

resource "aws_s3_bucket_server_side_encryption_configuration" "${bucket.resource_name!("bucket_" + (bucket?index + 1))}_sse" {
  bucket = aws_s3_bucket.${bucket.resource_name!("bucket_" + (bucket?index + 1))}.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "${bucket.sse_algorithm!"AES256"}"
    }
  }
}
</#if>

resource "aws_s3_bucket_public_access_block" "${bucket.resource_name!("bucket_" + (bucket?index + 1))}_public_access" {
  bucket = aws_s3_bucket.${bucket.resource_name!("bucket_" + (bucket?index + 1))}.id

  block_public_acls       = ${bucket.block_public_acls!"true"}
  block_public_policy     = ${bucket.block_public_policy!"true"}
  ignore_public_acls      = ${bucket.ignore_public_acls!"true"}
  restrict_public_buckets = ${bucket.restrict_public_buckets!"true"}
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- RDS Instances                                                -->
<#-- ============================================================ -->
<#if s.rds?? && s.rds.enabled>
<#list s.rds.instances as db>

resource "aws_db_instance" "${db.resource_name!("db_" + (db?index + 1))}" {
  identifier        = "${db.identifier}"
  engine            = "${db.engine!"postgres"}"
  engine_version    = "${db.engine_version}"
  instance_class    = "${db.instance_class!"db.t3.medium"}"
  allocated_storage = ${db.allocated_storage!"20"}
<#if db.max_allocated_storage?has_content>
  max_allocated_storage = ${db.max_allocated_storage}
</#if>
  storage_type      = "${db.storage_type!"gp3"}"
  storage_encrypted = ${db.storage_encrypted!"true"}
<#if db.db_name?has_content>
  db_name           = "${db.db_name}"
</#if>
  username          = "${db.username}"
  password          = "CHANGE_ME_USE_SECRETS_MANAGER"
  multi_az               = ${db.multi_az!"false"}
  publicly_accessible    = ${db.publicly_accessible!"false"}
  backup_retention_period = ${db.backup_retention_period!"7"}
  skip_final_snapshot    = ${db.skip_final_snapshot!"false"}
<#if db.skip_final_snapshot?has_content && db.skip_final_snapshot == "false">
  final_snapshot_identifier = "${db.identifier}-final-snapshot"
</#if>
<#if db.vpc_security_group_refs?has_content>
  vpc_security_group_ids = [<#list db.vpc_security_group_refs?split(",") as ref><#if ref?trim?has_content>aws_security_group.${ref?trim}.id<#sep>, </#sep></#if></#list>]
</#if>
<#if db.name_tag?has_content>

  tags = {
    Name = "${db.name_tag}"
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- Load Balancers                                               -->
<#-- ============================================================ -->
<#if s.alb?? && s.alb.enabled>
<#list s.alb.instances as lb>

resource "aws_lb" "${lb.resource_name!("lb_" + (lb?index + 1))}" {
  name               = "${lb.name}"
  load_balancer_type = "${lb.load_balancer_type!"application"}"
  internal           = ${lb.internal!"false"}
  subnets            = [<#list lb.subnet_refs?split(",") as ref><#if ref?trim?has_content>aws_subnet.${ref?trim}.id<#sep>, </#sep></#if></#list>]
<#if lb.security_group_refs?has_content>
  security_groups    = [<#list lb.security_group_refs?split(",") as ref><#if ref?trim?has_content>aws_security_group.${ref?trim}.id<#sep>, </#sep></#if></#list>]
</#if>
  enable_deletion_protection = ${lb.enable_deletion_protection!"false"}
<#if lb.name_tag?has_content>

  tags = {
    Name = "${lb.name_tag}"
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- IAM Roles                                                    -->
<#-- ============================================================ -->
<#if s.iam_role?? && s.iam_role.enabled>
<#list s.iam_role.instances as role>

resource "aws_iam_role" "${role.resource_name!("role_" + (role?index + 1))}" {
  name        = "${role.role_name}"
<#if role.description?has_content>
  description = "${role.description}"
</#if>

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "${role.service_principal!"ec2.amazonaws.com"}"
        }
      }
    ]
  })
}
<#if role.managed_policy_arns?has_content>
<#list role.managed_policy_arns?split("\n") as arn>
<#if arn?trim?has_content>

resource "aws_iam_role_policy_attachment" "${role.resource_name!("role_" + (role?index + 1))}_policy_${arn?index}" {
  role       = aws_iam_role.${role.resource_name!("role_" + (role?index + 1))}.name
  policy_arn = "${arn?trim}"
}
</#if>
</#list>
</#if>
<#if role.service_principal?has_content && role.service_principal == "ec2.amazonaws.com">

resource "aws_iam_instance_profile" "${role.resource_name!("role_" + (role?index + 1))}_profile" {
  name = "${role.role_name}Profile"
  role = aws_iam_role.${role.resource_name!("role_" + (role?index + 1))}.name
}
</#if>
</#list>
</#if>
<#-- ============================================================ -->
<#-- CloudWatch Log Groups                                        -->
<#-- ============================================================ -->
<#if s.cloudwatch_log_group?? && s.cloudwatch_log_group.enabled>
<#list s.cloudwatch_log_group.instances as lg>

resource "aws_cloudwatch_log_group" "${lg.resource_name!("log_group_" + (lg?index + 1))}" {
  name              = "${lg.log_group_name}"
<#if lg.retention_in_days?has_content>
  retention_in_days = ${lg.retention_in_days!"30"}
</#if>
<#if lg.kms_key_id?has_content>
  kms_key_id        = "${lg.kms_key_id}"
</#if>
<#if lg.name_tag?has_content>

  tags = {
    Name = "${lg.name_tag}"
  }
</#if>
}
</#list>
</#if>
<#-- ============================================================ -->
<#-- Outputs                                                      -->
<#-- ============================================================ -->
<#if s.outputs?? && s.outputs.enabled>
<#list s.outputs.instances as out>

output "${out.output_name!("output_" + (out?index + 1))}" {
<#if out.description?has_content>
  description = "${out.description}"
</#if>
  value     = ${out.output_value}
<#if out.sensitive?has_content && out.sensitive == "true">
  sensitive = true
</#if>
}
</#list>
</#if>
