<#-- Terraform AWS configuration generated by InfraForge -->
<#-- Provider: ${cloud} | Region: ${region} -->

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "${region}"
}

resource "aws_instance" "${resource_name}" {
  ami           = "${ami_id}"
  instance_type = "${instance_type}"
<#if instance_count?has_content && instance_count != "1">
  count         = ${instance_count}
</#if>
<#if name_tag?has_content>

  tags = {
    Name = "${name_tag}"
  }
</#if>
}
