<#-- Docker Compose — generated by InfraForge -->
<#assign s = sections>
<#assign meta = s.compose_meta.instances[0]>
<#-- Helper: parse textarea lines into YAML list items -->
<#macro yamlListItems data indent>
<#if data?has_content>
<#list data?split("\n") as item>
<#if item?trim?has_content>
${" "?left_pad(indent)}- ${item?trim}
</#if>
</#list>
</#if>
</#macro>
<#-- Helper: parse KEY=VALUE textarea into YAML env entries -->
<#macro envEntries data indent>
<#if data?has_content>
<#list data?split("\n") as line>
<#if line?trim?has_content>
${" "?left_pad(indent)}- ${line?trim}
</#list>
</#if>
</#macro>
version: "${meta.compose_version!"3.9"}"
<#if meta.project_name?has_content>
name: ${meta.project_name}
</#if>

services:
<#-- ============================================================ -->
<#-- Services                                                      -->
<#-- ============================================================ -->
<#list s.service.instances as svc>
<#if svc.svc_name?has_content>
  ${svc.svc_name}:
<#if svc.svc_image?has_content && !(svc.svc_build_context?has_content)>
    image: ${svc.svc_image}
</#if>
<#if svc.svc_build_context?has_content>
    build:
      context: ${svc.svc_build_context}
<#if svc.svc_build_dockerfile?has_content>
      dockerfile: ${svc.svc_build_dockerfile}
</#if>
<#if svc.svc_image?has_content>
    image: ${svc.svc_image}
</#if>
</#if>
<#if svc.svc_container_name?has_content>
    container_name: ${svc.svc_container_name}
</#if>
<#if svc.svc_restart?has_content>
    restart: ${svc.svc_restart}
</#if>
<#if svc.svc_command?has_content>
    command: ${svc.svc_command}
</#if>
<#if svc.svc_user?has_content>
    user: "${svc.svc_user}"
</#if>
<#if svc.svc_ports?has_content>
    ports:
<@yamlListItems data=svc.svc_ports indent=6 />
</#if>
<#if svc.svc_env_vars?has_content || svc.svc_env_file?has_content>
    environment:
<#if svc.svc_env_vars?has_content>
<#list svc.svc_env_vars?split("\n") as ev>
<#if ev?trim?has_content>
      - ${ev?trim}
</#if>
</#list>
</#if>
<#if svc.svc_env_file?has_content>
    env_file:
      - ${svc.svc_env_file}
</#if>
</#if>
<#if svc.svc_volumes?has_content>
    volumes:
<@yamlListItems data=svc.svc_volumes indent=6 />
</#if>
<#if svc.svc_networks?has_content>
    networks:
<@yamlListItems data=svc.svc_networks indent=6 />
</#if>
<#if svc.svc_depends_on?has_content>
    depends_on:
<@yamlListItems data=svc.svc_depends_on indent=6 />
</#if>
<#if svc.svc_healthcheck_cmd?has_content>
    healthcheck:
      test: ["CMD-SHELL", "${svc.svc_healthcheck_cmd}"]
      interval: ${svc.svc_healthcheck_interval!"10s"}
      retries: ${svc.svc_healthcheck_retries!"5"}
      timeout: 5s
      start_period: 10s
</#if>
<#if svc.svc_cpu_limit?has_content || svc.svc_memory_limit?has_content>
    deploy:
      resources:
        limits:
<#if svc.svc_cpu_limit?has_content>
          cpus: "${svc.svc_cpu_limit}"
</#if>
<#if svc.svc_memory_limit?has_content>
          memory: ${svc.svc_memory_limit}
</#if>
<#if svc.svc_memory_reservation?has_content>
        reservations:
          memory: ${svc.svc_memory_reservation}
</#if>
</#if>
</#if>
</#list>
<#-- ============================================================ -->
<#-- Named Volumes                                                 -->
<#-- ============================================================ -->
<#if s.volume?? && s.volume.enabled && s.volume.instances?has_content>

volumes:
<#list s.volume.instances as vol>
<#if vol.vol_name?has_content>
  ${vol.vol_name}:
<#if (vol.vol_external!"false") == "true">
    external: true
<#else>
    driver: ${vol.vol_driver!"local"}
</#if>
</#if>
</#list>
</#if>
<#-- ============================================================ -->
<#-- Named Networks                                                -->
<#-- ============================================================ -->
<#if s.network?? && s.network.enabled && s.network.instances?has_content>

networks:
<#list s.network.instances as net>
<#if net.net_name?has_content>
  ${net.net_name}:
<#if (net.net_external!"false") == "true">
    external: true
<#else>
    driver: ${net.net_driver!"bridge"}
<#if net.net_subnet?has_content>
    ipam:
      config:
        - subnet: ${net.net_subnet}
</#if>
</#if>
</#if>
</#list>
</#if>
