<#-- Vagrantfile — generated by InfraForge -->
<#assign s = sections>
<#assign vm = s.vm.instances[0]>
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
<#-- ─── Multi-machine configuration ──────────────────────────── -->
<#if s.multi_machine?? && s.multi_machine.enabled && s.multi_machine.instances?has_content>
<#list s.multi_machine.instances as m>
<#if m.machine_name?has_content>

  config.vm.define "${m.machine_name}" do |${m.machine_name}|
    ${m.machine_name}.vm.box      = "${m.machine_box!"ubuntu/jammy64"}"
<#if m.machine_hostname?has_content>
    ${m.machine_name}.vm.hostname = "${m.machine_hostname}"
</#if>
<#if m.machine_ip?has_content>
    ${m.machine_name}.vm.network "private_network", ip: "${m.machine_ip}"
</#if>
<#if m.machine_forwarded_port?has_content && m.machine_host_port?has_content>
    ${m.machine_name}.vm.network "forwarded_port", guest: ${m.machine_forwarded_port}, host: ${m.machine_host_port}
</#if>

    ${m.machine_name}.vm.provider "virtualbox" do |vb|
      vb.name   = "${m.machine_name}"
      vb.memory = "${m.machine_memory!"2048"}"
      vb.cpus   = "${m.machine_cpus!"2"}"
    end
<#if m.shell_provision?has_content>

    ${m.machine_name}.vm.provision "shell", inline: <<-SHELL
      ${m.shell_provision}
    SHELL
</#if>
  end
</#if>
</#list>
<#else>
<#-- ─── Single machine configuration ─────────────────────────── -->

  # Box
  config.vm.box     = "${vm.box!"ubuntu/jammy64"}"
<#if vm.box_version?has_content>
  config.vm.box_version = "${vm.box_version}"
</#if>
  config.vm.hostname = "${vm.hostname!vm.vm_name!"vagrant"}"

  # VM identity
  config.vm.define "${vm.vm_name!"default"}"
<#-- ─── Forwarded Ports ─────────────────────────────────────── -->
<#if s.network_forwarded?? && s.network_forwarded.enabled>
<#list s.network_forwarded.instances as port>
<#if port.guest_port?has_content && port.host_port?has_content>

  config.vm.network "forwarded_port",
    guest: ${port.guest_port},
    host:  ${port.host_port}<#if port.protocol?has_content && port.protocol != "tcp">,
    protocol: "${port.protocol}"</#if><#if port.host_ip?has_content>,
    host_ip: "${port.host_ip}"</#if><#if port.auto_correct == "true">,
    auto_correct: true</#if>
</#if>
</#list>
</#if>
<#-- ─── Private Network ───────────────────────────────────────── -->
<#if s.network_private?? && s.network_private.enabled>
<#assign priv = s.network_private.instances[0]>

  config.vm.network "private_network"<#if priv.private_ip?has_content>,
    ip: "${priv.private_ip}"<#else>,
    type: "dhcp"</#if><#if priv.netmask?has_content>,
    netmask: "${priv.netmask}"</#if>
</#if>
<#-- ─── Public Network ────────────────────────────────────────── -->
<#if s.network_public?? && s.network_public.enabled>
<#assign pub = s.network_public.instances[0]>

  config.vm.network "public_network"<#if pub.bridge_interface?has_content>,
    bridge: "${pub.bridge_interface}"</#if><#if pub.public_ip?has_content>,
    ip: "${pub.public_ip}"</#if>
</#if>
<#-- ─── Synced Folders ─────────────────────────────────────────── -->
<#if s.synced_folder?? && s.synced_folder.enabled>
<#list s.synced_folder.instances as folder>
<#if folder.host_path?has_content && folder.guest_path?has_content>

  config.vm.synced_folder "${folder.host_path}", "${folder.guest_path}"<#if folder.sync_type?has_content>,
    type: "${folder.sync_type}"</#if><#if folder.disabled == "true">,
    disabled: true</#if><#if folder.create == "true">,
    create: true</#if>
</#if>
</#list>
</#if>
<#-- ─── SSH Configuration ─────────────────────────────────────── -->
<#if s.ssh?? && s.ssh.enabled>
<#assign ssh = s.ssh.instances[0]>

  config.ssh.username              = "${ssh.ssh_username!"vagrant"}"
  config.ssh.insert_key            = ${ssh.insert_key!"true"}
<#if ssh.private_key_path?has_content>
  config.ssh.private_key_path      = "${ssh.private_key_path}"
</#if>
  config.ssh.forward_agent         = ${ssh.forward_agent!"false"}
  config.ssh.forward_x11           = ${ssh.forward_x11!"false"}
<#if ssh.connect_timeout?has_content>
  config.ssh.connect_timeout       = ${ssh.connect_timeout}
</#if>
</#if>
<#-- ─── VirtualBox Provider ───────────────────────────────────── -->
<#if s.provider_virtualbox?? && s.provider_virtualbox.enabled>
<#assign vbox = s.provider_virtualbox.instances[0]>

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "${vbox.vb_name!vm.vm_name!"vagrant"}"
    vb.memory = "${vm.memory!"2048"}"
    vb.cpus   = ${vm.cpus!"2"}
    vb.gui    = ${vbox.gui!"false"}
<#if vbox.vb_customize?has_content>
    # Custom VBoxManage flags
<#list vbox.vb_customize?split("\n") as line>
<#if line?trim?has_content>
    vb.customize ${line?trim}
</#if>
</#list>
</#if>
<#if vbox.linked_clone == "true">
    vb.linked_clone = true
</#if>
<#if vbox.check_guest_additions == "false">
    vb.check_guest_additions = false
</#if>
  end
<#else>

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "${vm.memory!"2048"}"
    vb.cpus   = ${vm.cpus!"2"}
  end
</#if>
<#-- ─── VMware Provider ───────────────────────────────────────── -->
<#if s.provider_vmware?? && s.provider_vmware.enabled>
<#assign vmw = s.provider_vmware.instances[0]>

  config.vm.provider "vmware_desktop" do |vmw|
    vmw.vmx["displayName"] = "${vmw.vmx_display_name!vm.vm_name!"vagrant"}"
    vmw.vmx["memsize"]     = "${vm.memory!"2048"}"
    vmw.vmx["numvcpus"]    = "${vm.cpus!"2"}"
    vmw.gui                = ${vmw.gui!"false"}
<#if vmw.linked_clone == "true">
    vmw.linked_clone       = true
</#if>
  end
</#if>
<#-- ─── Shell Provisioner ─────────────────────────────────────── -->
<#if s.provision_shell?? && s.provision_shell.enabled>
<#list s.provision_shell.instances as prov>
<#if prov.inline_script?has_content>

  config.vm.provision "shell"<#if prov.provision_name?has_content>, name: "${prov.provision_name}"</#if>,
    privileged: ${prov.privileged!"true"},
    inline: <<-SHELL
      ${prov.inline_script}
    SHELL
<#elseif prov.script_path?has_content>

  config.vm.provision "shell"<#if prov.provision_name?has_content>, name: "${prov.provision_name}"</#if>,
    privileged: ${prov.privileged!"true"},
    path: "${prov.script_path}"<#if prov.script_args?has_content>,
    args: "${prov.script_args}"</#if>
</#if>
</#list>
</#if>
<#-- ─── Ansible Provisioner ───────────────────────────────────── -->
<#if s.provision_ansible?? && s.provision_ansible.enabled>
<#assign ap = s.provision_ansible.instances[0]>

  config.vm.provision "ansible" do |ansible|
    ansible.playbook       = "${ap.ansible_playbook!"playbook.yml"}"
<#if ap.ansible_inventory?has_content>
    ansible.inventory_path = "${ap.ansible_inventory}"
</#if>
    ansible.become         = ${ap.ansible_become!"false"}
<#if ap.ansible_limit?has_content>
    ansible.limit          = "${ap.ansible_limit}"
</#if>
<#if ap.ansible_extra_vars?has_content>
    ansible.extra_vars = {
<#list ap.ansible_extra_vars?split("\n") as line>
<#if line?trim?has_content>
      ${line?trim},
</#if>
</#list>
    }
</#if>
    ansible.verbose        = ${ap.ansible_verbose!"false"}
  end
</#if>
<#-- ─── File Provisioner ──────────────────────────────────────── -->
<#if s.provision_file?? && s.provision_file.enabled>
<#list s.provision_file.instances as prov>
<#if prov.source?has_content && prov.destination?has_content>

  config.vm.provision "file",
    source:      "${prov.source}",
    destination: "${prov.destination}"
</#if>
</#list>
</#if>
<#-- ─── Docker Provisioner ────────────────────────────────────── -->
<#if s.provision_docker?? && s.provision_docker.enabled>
<#assign dp = s.provision_docker.instances[0]>

  config.vm.provision "docker" do |d|
<#if dp.docker_images?has_content>
<#list dp.docker_images?split("\n") as img>
<#if img?trim?has_content>
    d.pull_images "${img?trim}"
</#if>
</#list>
</#if>
<#if dp.docker_run_image?has_content>
    d.run "${dp.docker_run_image}",
      args: "${dp.docker_run_args!""}"
</#if>
  end
</#if>
</#if>

end
