<#-- Kubernetes Manifests — generated by InfraForge -->
<#assign s = sections>
<#-- Helper: parse KEY=VALUE textarea into indented YAML map entries -->
<#-- Uses keep_before/keep_after to handle values containing = -->
<#macro yamlMap data indent>
<#if data?has_content>
<#list data?split("\n") as line>
<#assign t = line?trim>
<#if t?has_content && t?contains("=")>
<#assign spaces><#list 1..indent as i> </#list></#assign>
${spaces}${t?keep_before("=")}: "${t?keep_after("=")}"
</#if>
</#list>
</#if>
</#macro>
<#-- ============================================================ -->
<#-- Namespace                                                     -->
<#-- ============================================================ -->
<#if s.namespace?? && s.namespace.enabled>
<#assign ns = s.namespace.instances[0]>
apiVersion: v1
kind: Namespace
metadata:
  name: ${ns.namespace_name!"my-app"}
  labels:
    environment: ${ns.namespace_env_label!"production"}
---
</#if>
<#-- ============================================================ -->
<#-- ServiceAccount                                                -->
<#-- ============================================================ -->
<#if s.service_account?? && s.service_account.enabled>
<#assign sa = s.service_account.instances[0]>
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${sa.sa_name!"my-app-sa"}
  namespace: ${sa.sa_namespace!"default"}
<#if sa.sa_annotation_key?has_content>
  annotations:
    ${sa.sa_annotation_key}: "${sa.sa_annotation_value!""}"
</#if>
automountServiceAccountToken: ${sa.sa_automount_token!"false"}
---
</#if>
<#-- ============================================================ -->
<#-- ConfigMaps                                                    -->
<#-- ============================================================ -->
<#if s.configmap?? && s.configmap.enabled>
<#list s.configmap.instances as cm>
<#if cm.cm_name?has_content>
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${cm.cm_name}
  namespace: ${cm.cm_namespace!"default"}
<#if cm.cm_data?has_content>
data:
<@yamlMap data=cm.cm_data indent=2 />
</#if>
---
</#if>
</#list>
</#if>
<#-- ============================================================ -->
<#-- Secrets                                                       -->
<#-- ============================================================ -->
<#if s.secret?? && s.secret.enabled>
<#list s.secret.instances as sec>
<#if sec.secret_name?has_content>
apiVersion: v1
kind: Secret
metadata:
  name: ${sec.secret_name}
  namespace: ${sec.secret_namespace!"default"}
type: ${sec.secret_type!"Opaque"}
<#if sec.secret_data?has_content>
data:
<@yamlMap data=sec.secret_data indent=2 />
</#if>
---
</#if>
</#list>
</#if>
<#-- ============================================================ -->
<#-- PersistentVolumeClaims                                        -->
<#-- ============================================================ -->
<#if s.persistent_volume_claim?? && s.persistent_volume_claim.enabled>
<#list s.persistent_volume_claim.instances as pvc>
<#if pvc.pvc_name?has_content>
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${pvc.pvc_name}
  namespace: ${pvc.pvc_namespace!"default"}
spec:
  accessModes:
    - ${pvc.pvc_access_mode!"ReadWriteOnce"}
<#if pvc.pvc_storage_class?has_content>
  storageClassName: ${pvc.pvc_storage_class}
</#if>
  resources:
    requests:
      storage: ${pvc.pvc_storage_size!"10Gi"}
---
</#if>
</#list>
</#if>
<#-- ============================================================ -->
<#-- Deployment                                                    -->
<#-- ============================================================ -->
<#assign dep = s.deployment.instances[0]>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${dep.app_name!"my-app"}
  namespace: ${dep.namespace!"default"}
  labels:
    app: ${dep.app_name!"my-app"}
spec:
  replicas: ${dep.replicas!"2"}
  selector:
    matchLabels:
      app: ${dep.app_name!"my-app"}
  strategy:
    type: ${dep.update_strategy!"RollingUpdate"}
<#if (dep.update_strategy!"RollingUpdate") == "RollingUpdate">
    rollingUpdate:
      maxSurge: ${dep.max_surge!"1"}
      maxUnavailable: ${dep.max_unavailable!"0"}
</#if>
  template:
    metadata:
      labels:
        app: ${dep.app_name!"my-app"}
    spec:
<#if dep.service_account_name?has_content>
      serviceAccountName: ${dep.service_account_name}
</#if>
      containers:
        - name: ${dep.app_name!"my-app"}
          image: ${dep.image!"nginx:1.25"}
          imagePullPolicy: ${dep.image_pull_policy!"IfNotPresent"}
          ports:
            - containerPort: ${dep.container_port!"8080"}
<#if dep.cpu_request?has_content || dep.memory_request?has_content || dep.cpu_limit?has_content || dep.memory_limit?has_content>
          resources:
            requests:
<#if dep.cpu_request?has_content>
              cpu: "${dep.cpu_request}"
</#if>
<#if dep.memory_request?has_content>
              memory: "${dep.memory_request}"
</#if>
            limits:
<#if dep.cpu_limit?has_content>
              cpu: "${dep.cpu_limit}"
</#if>
<#if dep.memory_limit?has_content>
              memory: "${dep.memory_limit}"
</#if>
</#if>
<#if dep.env_configmap_ref?has_content || dep.env_secret_ref?has_content>
          envFrom:
<#if dep.env_configmap_ref?has_content>
            - configMapRef:
                name: ${dep.env_configmap_ref}
</#if>
<#if dep.env_secret_ref?has_content>
            - secretRef:
                name: ${dep.env_secret_ref}
</#if>
</#if>
<#if dep.volume_mount_name?has_content && dep.volume_mount_path?has_content>
          volumeMounts:
            - name: ${dep.volume_mount_name}
              mountPath: ${dep.volume_mount_path}
</#if>
<#if dep.liveness_path?has_content>
          livenessProbe:
            httpGet:
              path: ${dep.liveness_path}
              port: ${dep.liveness_port!"8080"}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
</#if>
<#if dep.readiness_path?has_content>
          readinessProbe:
            httpGet:
              path: ${dep.readiness_path}
              port: ${dep.readiness_port!"8080"}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
</#if>
<#if dep.volume_mount_name?has_content>
      volumes:
        - name: ${dep.volume_mount_name}
          persistentVolumeClaim:
            claimName: ${dep.volume_mount_name}
</#if>
      restartPolicy: ${dep.restart_policy!"Always"}
<#-- ============================================================ -->
<#-- Service                                                       -->
<#-- ============================================================ -->
<#if s.service?? && s.service.enabled>
<#assign svc = s.service.instances[0]>
---
apiVersion: v1
kind: Service
metadata:
  name: ${svc.svc_name!"my-app-svc"}
  namespace: ${svc.svc_namespace!"default"}
spec:
  type: ${svc.svc_type!"ClusterIP"}
  selector:
    app: ${svc.svc_selector_app!"my-app"}
  ports:
    - port: ${svc.svc_port!"80"}
      targetPort: ${svc.svc_target_port!"8080"}
      protocol: TCP
<#if svc.svc_node_port?has_content && (svc.svc_type!"ClusterIP") != "ClusterIP">
      nodePort: ${svc.svc_node_port}
</#if>
<#if (svc.svc_session_affinity!"None") != "None">
  sessionAffinity: ${svc.svc_session_affinity}
</#if>
</#if>
<#-- ============================================================ -->
<#-- Ingress                                                       -->
<#-- ============================================================ -->
<#if s.ingress?? && s.ingress.enabled>
<#assign ing = s.ingress.instances[0]>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${ing.ingress_name!"my-app-ingress"}
  namespace: ${ing.ingress_namespace!"default"}
  annotations:
    kubernetes.io/ingress.class: "${ing.ingress_class!"nginx"}"
spec:
<#if (ing.ingress_tls_enabled!"false") == "true">
  tls:
    - hosts:
        - ${ing.ingress_host!"myapp.example.com"}
<#if ing.ingress_tls_secret?has_content>
      secretName: ${ing.ingress_tls_secret}
</#if>
</#if>
  rules:
    - host: ${ing.ingress_host!"myapp.example.com"}
      http:
        paths:
          - path: ${ing.ingress_path!"/"}
            pathType: ${ing.ingress_path_type!"Prefix"}
            backend:
              service:
                name: ${ing.ingress_service_name!"my-app-svc"}
                port:
                  number: ${ing.ingress_service_port!"80"}
</#if>
<#-- ============================================================ -->
<#-- HorizontalPodAutoscaler                                       -->
<#-- ============================================================ -->
<#if s.hpa?? && s.hpa.enabled>
<#assign hpa = s.hpa.instances[0]>
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${hpa.hpa_name!"my-app-hpa"}
  namespace: ${hpa.hpa_namespace!"default"}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${hpa.hpa_target_name!"my-app"}
  minReplicas: ${hpa.hpa_min_replicas!"2"}
  maxReplicas: ${hpa.hpa_max_replicas!"10"}
  metrics:
<#if hpa.hpa_cpu_target?has_content>
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${hpa.hpa_cpu_target!"70"}
</#if>
<#if hpa.hpa_memory_target?has_content>
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: ${hpa.hpa_memory_target}
</#if>
</#if>
