<#-- Ansible Playbook — generated by InfraForge -->
<#assign s = sections>
<#assign pb = s.playbook.instances[0]>
<#-- Helper: comma-separated string → YAML list items -->
<#macro yamlList value>
<#list value?split(",") as item><#if item?trim?has_content>
      - ${item?trim}</#if></#list>
</#macro>
<#-- Helper: emit common task tail fields (when/notify/tags/ignore_errors) -->
<#macro taskTail task>
<#if task.when_condition?has_content>
      when: ${task.when_condition}
</#if>
<#if task.notify?has_content>
      notify: "${task.notify}"
</#if>
<#if task.tags?has_content>
      tags: [<#list task.tags?split(",") as t><#if t?trim?has_content>"${t?trim}"<#sep>, </#sep></#if></#list>]
</#if>
<#if task.ignore_errors?has_content && task.ignore_errors == "true">
      ignore_errors: true
</#if>
</#macro>
---
- name: "${pb.playbook_name!"My Playbook"}"
  hosts: ${pb.hosts!"all"}
  gather_facts: ${pb.gather_facts!"true"}
  become: ${pb.become!"false"}
<#if pb.become == "true">
  become_method: ${pb.become_method!"sudo"}
<#if pb.become_user?has_content>
  become_user: ${pb.become_user!"root"}
</#if>
</#if>
  connection: ${pb.connection!"ssh"}
  strategy: ${pb.strategy!"linear"}
<#if pb.serial?has_content>
  serial: ${pb.serial}
</#if>
<#if pb.any_errors_fatal == "true">
  any_errors_fatal: true
</#if>
<#if pb.max_fail_percentage?has_content>
  max_fail_percentage: ${pb.max_fail_percentage}
</#if>
<#if pb.environment_key?has_content>

  environment:
    ${pb.environment_key}: "${pb.environment_value!""}"
</#if>
<#-- ─── Variables ──────────────────────────────────────────── -->
<#if s.variables?? && s.variables.enabled && s.variables.instances?has_content>

  vars:
<#list s.variables.instances as v>
<#if v.var_name?has_content>
    ${v.var_name}: ${v.var_value!""}
</#if>
</#list>
</#if>
<#-- ─── Pre-tasks ──────────────────────────────────────────── -->
<#if s.pre_tasks?? && s.pre_tasks.enabled && s.pre_tasks.instances?has_content>

  pre_tasks:
<#list s.pre_tasks.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.module == "assert">
      ansible.builtin.assert:
        that: ${task.command!"true"}
<#elseif task.module == "fail">
      ansible.builtin.fail:
        msg: "${task.command!"Failing as requested"}"
<#elseif task.module == "set_fact">
      ansible.builtin.set_fact:
        ${task.command!"result"}: true
<#elseif task.module == "debug">
      ansible.builtin.debug:
        msg: "${task.command!""}"
<#else>
      ansible.builtin.${task.module!"command"}:
        cmd: ${task.command!""}
</#if>
<#if task.when_condition?has_content>
      when: ${task.when_condition}
</#if>
</#if>
</#list>
</#if>
<#-- ─── Roles ──────────────────────────────────────────────── -->
<#if s.roles?? && s.roles.enabled && s.roles.instances?has_content>

  roles:
<#list s.roles.instances as role>
<#if role.role_name?has_content>
    - role: ${role.role_name}
      become: ${role.role_become!"false"}
<#if role.role_vars?has_content>
      vars:
<#list role.role_vars?split("\n") as line>
<#if line?trim?has_content>
        ${line?trim}
</#if>
</#list>
</#if>
<#if role.when_condition?has_content>
      when: ${role.when_condition}
</#if>
<#if role.tags?has_content>
      tags: [<#list role.tags?split(",") as t><#if t?trim?has_content>"${t?trim}"<#sep>, </#sep></#if></#list>]
</#if>
</#if>
</#list>
</#if>
<#-- ─── Tasks ──────────────────────────────────────────────── -->
<#assign hasTasks = (s.tasks_package?? && s.tasks_package.enabled) ||
                    (s.tasks_service?? && s.tasks_service.enabled) ||
                    (s.tasks_file?? && s.tasks_file.enabled) ||
                    (s.tasks_template?? && s.tasks_template.enabled) ||
                    (s.tasks_command?? && s.tasks_command.enabled) ||
                    (s.tasks_user?? && s.tasks_user.enabled) ||
                    (s.tasks_git?? && s.tasks_git.enabled) ||
                    (s.tasks_debug?? && s.tasks_debug.enabled) ||
                    (s.tasks_firewall?? && s.tasks_firewall.enabled) ||
                    (s.tasks_docker?? && s.tasks_docker.enabled) ||
                    (s.tasks_cron?? && s.tasks_cron.enabled)>
<#if hasTasks>

  tasks:
</#if>
<#-- Package tasks -->
<#if s.tasks_package?? && s.tasks_package.enabled>
<#list s.tasks_package.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.loop_items?has_content>
      ansible.builtin.${task.package_manager!"apt"}:
        name: "{{ item }}"
        state: ${task.package_state!"present"}
        update_cache: ${task.update_cache!"false"}
      loop:
<#list task.loop_items?split("\n") as item>
<#if item?trim?has_content>
        - ${item?trim}
</#if>
</#list>
<#else>
      ansible.builtin.${task.package_manager!"apt"}:
        name: <#if (task.packages!"")?contains(",")>[<#list task.packages?split(",") as p><#if p?trim?has_content>"${p?trim}"<#sep>, </#sep></#if></#list>]<#else>${task.packages!""}</#if>
        state: ${task.package_state!"present"}
        update_cache: ${task.update_cache!"false"}
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- Service tasks -->
<#if s.tasks_service?? && s.tasks_service.enabled>
<#list s.tasks_service.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.daemon_reload == "true">
      ansible.builtin.systemd:
        name: ${task.service_name!""}
        state: ${task.service_state!"started"}
        enabled: ${task.service_enabled!"true"}
        daemon_reload: true
<#else>
      ansible.builtin.service:
        name: ${task.service_name!""}
        state: ${task.service_state!"started"}
        enabled: ${task.service_enabled!"true"}
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- File tasks -->
<#if s.tasks_file?? && s.tasks_file.enabled>
<#list s.tasks_file.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
      ansible.builtin.${task.file_module!"copy"}:
<#if task.file_module == "file">
        path: ${task.dest!""}
        state: ${task.file_state!"present"}
        recurse: ${task.recurse!"false"}
<#elseif task.file_module == "lineinfile">
        path: ${task.dest!""}
        line: "${task.line!""}"
<#if task.regexp?has_content>
        regexp: "${task.regexp}"
</#if>
<#elseif task.file_module == "replace">
        path: ${task.dest!""}
        regexp: "${task.regexp!""}"
        replace: "${task.line!""}"
<#elseif task.file_module == "fetch">
        src: ${task.dest!""}
        dest: ${task.src!""}
        flat: true
<#else>
<#if task.content?has_content>
        content: |
          ${task.content?replace("\n", "\n          ")}
<#elseif task.src?has_content>
        src: ${task.src}
</#if>
        dest: ${task.dest!""}
</#if>
<#if task.owner?has_content>
        owner: ${task.owner}
</#if>
<#if task.group?has_content>
        group: ${task.group}
</#if>
<#if task.mode?has_content>
        mode: "${task.mode}"
</#if>
<#if task.backup?has_content && task.backup == "true">
        backup: true
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- Template tasks -->
<#if s.tasks_template?? && s.tasks_template.enabled>
<#list s.tasks_template.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
      ansible.builtin.template:
        src: ${task.template_src!""}
        dest: ${task.template_dest!""}
<#if task.owner?has_content>
        owner: ${task.owner}
</#if>
<#if task.group?has_content>
        group: ${task.group}
</#if>
<#if task.mode?has_content>
        mode: "${task.mode}"
</#if>
<#if task.backup == "true">
        backup: true
</#if>
<#if task.validate?has_content>
        validate: ${task.validate}
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- Command tasks -->
<#if s.tasks_command?? && s.tasks_command.enabled>
<#list s.tasks_command.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
      ansible.builtin.${task.command_module!"command"}:
        cmd: ${task.command!""}
<#if task.chdir?has_content>
        chdir: ${task.chdir}
</#if>
<#if task.creates?has_content>
        creates: ${task.creates}
</#if>
<#if task.removes?has_content>
        removes: ${task.removes}
</#if>
<#if task.environment_key?has_content>
      environment:
        ${task.environment_key}: "${task.environment_value!""}"
</#if>
<#if task.register_var?has_content>
      register: ${task.register_var}
</#if>
<#if task.loop_items?has_content>
      loop:
<#list task.loop_items?split("\n") as item>
<#if item?trim?has_content>
        - ${item?trim}
</#if>
</#list>
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- User tasks -->
<#if s.tasks_user?? && s.tasks_user.enabled>
<#list s.tasks_user.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
      ansible.builtin.user:
        name: ${task.username!""}
        state: ${task.user_state!"present"}
<#if task.user_groups?has_content>
        groups: ${task.user_groups}
        append: ${task.append_groups!"true"}
</#if>
<#if task.user_shell?has_content>
        shell: ${task.user_shell}
</#if>
<#if task.user_home?has_content>
        home: ${task.user_home}
</#if>
        create_home: ${task.create_home!"true"}
        system: ${task.system_user!"false"}
        password_lock: ${task.password_lock!"true"}
<#if task.comment?has_content>
        comment: "${task.comment}"
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- Git tasks -->
<#if s.tasks_git?? && s.tasks_git.enabled>
<#list s.tasks_git.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
      ansible.builtin.git:
        repo: ${task.git_repo!""}
        dest: ${task.git_dest!""}
        version: ${task.git_version!"main"}
<#if task.git_depth?has_content && task.git_depth != "0">
        depth: ${task.git_depth}
</#if>
        force: ${task.git_force!"false"}
        accept_hostkey: ${task.accept_hostkey!"true"}
<#if task.git_key_file?has_content>
        key_file: ${task.git_key_file}
</#if>
<#if task.register_var?has_content>
      register: ${task.register_var}
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- Debug / Assert / set_fact tasks -->
<#if s.tasks_debug?? && s.tasks_debug.enabled>
<#list s.tasks_debug.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.debug_module == "assert">
      ansible.builtin.assert:
        that:
          - ${task.msg!"true"}
<#elseif task.debug_module == "fail">
      ansible.builtin.fail:
        msg: "${task.msg!"Failing as requested"}"
<#elseif task.debug_module == "set_fact">
      ansible.builtin.set_fact:
        ${task.set_fact_key!"result"}: ${task.set_fact_value!"true"}
<#else>
      ansible.builtin.debug:
<#if task.var?has_content>
        var: ${task.var}
<#else>
        msg: "${task.msg!""}"
</#if>
<#if task.verbosity?has_content && task.verbosity != "0">
        verbosity: ${task.verbosity}
</#if>
</#if>
<#if task.when_condition?has_content>
      when: ${task.when_condition}
</#if>
<#if task.tags?has_content>
      tags: [<#list task.tags?split(",") as t><#if t?trim?has_content>"${t?trim}"<#sep>, </#sep></#if></#list>]
</#if>
</#if>
</#list>
</#if>
<#-- Firewall tasks -->
<#if s.tasks_firewall?? && s.tasks_firewall.enabled>
<#list s.tasks_firewall.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.firewall_module == "firewalld">
      ansible.posix.firewalld:
<#if task.firewalld_service?has_content>
        service: ${task.firewalld_service}
<#elseif task.port?has_content>
        port: ${task.port}/${task.proto!"tcp"}
</#if>
        zone: ${task.firewalld_zone!"public"}
        permanent: ${task.firewalld_permanent!"true"}
        state: ${task.firewalld_state!"enabled"}
<#else>
      community.general.ufw:
<#if task.fw_state?has_content && task.fw_state != "">
        state: ${task.fw_state}
</#if>
<#if task.port?has_content>
        rule: ${task.rule!"allow"}
        port: "${task.port}"
        proto: ${task.proto!"tcp"}
<#if task.from_ip?has_content>
        from_ip: ${task.from_ip}
</#if>
</#if>
</#if>
<#if task.when_condition?has_content>
      when: ${task.when_condition}
</#if>
<#if task.tags?has_content>
      tags: [<#list task.tags?split(",") as t><#if t?trim?has_content>"${t?trim}"<#sep>, </#sep></#if></#list>]
</#if>
</#if>
</#list>
</#if>
<#-- Docker tasks -->
<#if s.tasks_docker?? && s.tasks_docker.enabled>
<#list s.tasks_docker.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.docker_module == "docker_compose">
      community.docker.docker_compose:
        project_src: ${task.compose_file!"/var/app"}
        state: ${task.docker_state!"present"}
<#elseif task.docker_module == "docker_image">
      community.docker.docker_image:
        name: ${task.image!""}
        source: <#if task.pull_image!"true" == "true">pull<#else>local</#if>
        state: ${task.docker_state!"present"}
<#elseif task.docker_module == "docker_network">
      community.docker.docker_network:
        name: ${task.networks!"app_network"}
        state: ${task.docker_state!"present"}
<#elseif task.docker_module == "docker_volume">
      community.docker.docker_volume:
        name: ${task.container_name!"app_volume"}
        state: ${task.docker_state!"present"}
<#else>
      community.docker.docker_container:
        name: ${task.container_name!"app"}
        image: ${task.image!""}
        state: ${task.docker_state!"started"}
        pull: ${task.pull_image!"true"}
        restart_policy: ${task.restart_policy!"unless-stopped"}
<#if task.ports?has_content>
        ports:
<#list task.ports?split(",") as p>
<#if p?trim?has_content>
          - "${p?trim}"
</#if>
</#list>
</#if>
<#if task.volumes?has_content>
        volumes:
<#list task.volumes?split("\n") as v>
<#if v?trim?has_content>
          - "${v?trim}"
</#if>
</#list>
</#if>
<#if task.networks?has_content>
        networks:
          - name: ${task.networks}
</#if>
<#if task.env_vars?has_content>
        env:
<#list task.env_vars?split("\n") as line>
<#if line?trim?has_content && line?contains("=")>
          ${line?keep_before("=")}: "${line?keep_after("=")}"
</#if>
</#list>
</#if>
</#if>
<@taskTail task=task />
</#if>
</#list>
</#if>
<#-- Cron tasks -->
<#if s.tasks_cron?? && s.tasks_cron.enabled>
<#list s.tasks_cron.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
      ansible.builtin.cron:
        name: "${task.cron_name!task.task_name}"
        minute: "${task.cron_minute!"0"}"
        hour: "${task.cron_hour!"2"}"
        day: "${task.cron_day!"*"}"
        month: "${task.cron_month!"*"}"
        weekday: "${task.cron_weekday!"*"}"
        job: "${task.cron_job!""}"
        user: ${task.cron_user!"root"}
        state: ${task.cron_state!"present"}
<#if task.cron_disabled == "true">
        disabled: true
</#if>
<#if task.when_condition?has_content>
      when: ${task.when_condition}
</#if>
<#if task.tags?has_content>
      tags: [<#list task.tags?split(",") as t><#if t?trim?has_content>"${t?trim}"<#sep>, </#sep></#if></#list>]
</#if>
</#if>
</#list>
</#if>
<#-- ─── Post-tasks ────────────────────────────────────────── -->
<#if s.post_tasks?? && s.post_tasks.enabled && s.post_tasks.instances?has_content>

  post_tasks:
<#list s.post_tasks.instances as task>
<#if task.task_name?has_content>

    - name: "${task.task_name}"
<#if task.module == "assert">
      ansible.builtin.assert:
        that: ${task.command!"true"}
<#elseif task.module == "debug">
      ansible.builtin.debug:
        msg: "${task.command!""}"
<#elseif task.module == "uri">
      ansible.builtin.uri:
        url: ${task.command!"http://localhost"}
        status_code: 200
<#elseif task.module == "wait_for">
      ansible.builtin.wait_for:
        port: ${task.command!"80"}
        timeout: 30
<#else>
      ansible.builtin.${task.module!"command"}:
        cmd: ${task.command!""}
</#if>
<#if task.register_var?has_content>
      register: ${task.register_var}
</#if>
<#if task.when_condition?has_content>
      when: ${task.when_condition}
</#if>
</#if>
</#list>
</#if>
<#-- ─── Handlers ─────────────────────────────────────────── -->
<#if s.handlers?? && s.handlers.enabled && s.handlers.instances?has_content>

  handlers:
<#list s.handlers.instances as handler>
<#if handler.handler_name?has_content>

    - name: "${handler.handler_name}"
<#if handler.listen?has_content>
      listen: "${handler.listen}"
</#if>
<#if handler.handler_module == "systemd">
      ansible.builtin.systemd:
        name: ${handler.handler_service!""}
        state: ${handler.handler_state!"restarted"}
        daemon_reload: ${handler.handler_daemon_reload!"false"}
<#elseif handler.handler_module == "command">
      ansible.builtin.command:
        cmd: ${handler.handler_command!""}
<#elseif handler.handler_module == "shell">
      ansible.builtin.shell:
        cmd: ${handler.handler_command!""}
<#elseif handler.handler_module == "debug">
      ansible.builtin.debug:
        msg: "Handler '${handler.handler_name}' triggered"
<#else>
      ansible.builtin.service:
        name: ${handler.handler_service!""}
        state: ${handler.handler_state!"restarted"}
</#if>
</#if>
</#list>
</#if>
