<#-- Dockerfile — generated by InfraForge -->
<#assign s = sections>
<#assign base = s.base.instances[0]>
<#assign wd = s.workdir.instances[0]>
<#assign ep = s.entrypoint.instances[0]>
<#-- ============================================================ -->
<#-- Multi-stage build — build stage                              -->
<#-- ============================================================ -->
<#if (base.use_build_stage!"false") == "true">
FROM ${base.build_stage_image!"node:20-alpine"} AS builder

WORKDIR ${wd.workdir_path!"/app"}
<#if s.labels?? && s.labels.enabled>
<#assign lbl = s.labels.instances[0]>

LABEL maintainer="${lbl.label_maintainer!""}" \
      version="${lbl.label_version!""}" \
      description="${lbl.label_description!""}"
</#if>
<#if s.env_vars?? && s.env_vars.enabled>

<#list s.env_vars.instances as ev>
<#if ev.env_key?has_content>
ENV ${ev.env_key}="${ev.env_value!""}"
</#if>
</#list>
</#if>
<#if s.copy_deps?? && s.copy_deps.enabled>
<#assign cd = s.copy_deps.instances[0]>
<#if cd.dep_files?has_content>

COPY <#list cd.dep_files?split("\n") as f><#if f?trim?has_content>${f?trim} </#if></#list>./
</#if>
</#if>
<#if s.install_deps?? && s.install_deps.enabled>
<#assign id_sec = s.install_deps.instances[0]>

RUN ${id_sec.install_cmd!"npm ci"}
</#if>
<#if s.copy_source?? && s.copy_source.enabled>
<#assign cs = s.copy_source.instances[0]>

COPY ${cs.copy_src!"."} ${cs.copy_dest!"."}
</#if>
<#if s.build_cmd?? && s.build_cmd.enabled>
<#assign bc = s.build_cmd.instances[0]>

RUN ${bc.build_command!"npm run build"}
</#if>

<#-- ============================================================ -->
<#-- Multi-stage build — runtime stage                            -->
<#-- ============================================================ -->
FROM ${base.runtime_stage_image!base.base_image!"node:20-alpine"}

WORKDIR ${wd.workdir_path!"/app"}

COPY --from=builder ${wd.workdir_path!"/app"} ${wd.workdir_path!"/app"}

<#else>
<#-- ============================================================ -->
<#-- Single-stage build                                           -->
<#-- ============================================================ -->
FROM ${base.base_image!"node:20-alpine"}

WORKDIR ${wd.workdir_path!"/app"}
<#if s.labels?? && s.labels.enabled>
<#assign lbl = s.labels.instances[0]>

LABEL maintainer="${lbl.label_maintainer!""}" \
      version="${lbl.label_version!""}" \
      description="${lbl.label_description!""}"
</#if>
<#if s.env_vars?? && s.env_vars.enabled>

<#list s.env_vars.instances as ev>
<#if ev.env_key?has_content>
ENV ${ev.env_key}="${ev.env_value!""}"
</#if>
</#list>
</#if>
<#if s.run_commands?? && s.run_commands.enabled>

<#list s.run_commands.instances as rc>
<#if rc.run_cmd?has_content>
RUN ${rc.run_cmd}
</#if>
</#list>
</#if>
<#if s.copy_deps?? && s.copy_deps.enabled>
<#assign cd = s.copy_deps.instances[0]>
<#if cd.dep_files?has_content>

COPY <#list cd.dep_files?split("\n") as f><#if f?trim?has_content>${f?trim} </#if></#list>./
</#if>
</#if>
<#if s.install_deps?? && s.install_deps.enabled>
<#assign id_sec = s.install_deps.instances[0]>

RUN ${id_sec.install_cmd!"npm ci --only=production"}
</#if>
<#if s.copy_source?? && s.copy_source.enabled>
<#assign cs = s.copy_source.instances[0]>

COPY ${cs.copy_src!"."} ${cs.copy_dest!"."}
</#if>
<#if s.build_cmd?? && s.build_cmd.enabled>
<#assign bc = s.build_cmd.instances[0]>

RUN ${bc.build_command!"npm run build"}
</#if>
</#if>
<#-- ============================================================ -->
<#-- Non-root user                                                -->
<#-- ============================================================ -->
<#if s.user?? && s.user.enabled>
<#assign usr = s.user.instances[0]>

RUN addgroup --system ${usr.user_name!"appuser"} && \
    adduser --system --ingroup ${usr.user_name!"appuser"} --uid ${usr.user_uid!"1001"} ${usr.user_name!"appuser"}

USER ${usr.user_name!"appuser"}
</#if>
<#-- ============================================================ -->
<#-- Expose ports                                                 -->
<#-- ============================================================ -->
<#if s.expose?? && s.expose.enabled>

<#list s.expose.instances as port>
<#if port.expose_port?has_content>
EXPOSE ${port.expose_port}/${port.expose_protocol!"tcp"}
</#if>
</#list>
</#if>
<#-- ============================================================ -->
<#-- Healthcheck                                                  -->
<#-- ============================================================ -->
<#if s.healthcheck?? && s.healthcheck.enabled>
<#assign hc = s.healthcheck.instances[0]>

HEALTHCHECK --interval=${hc.healthcheck_interval!"30s"} \
            --timeout=${hc.healthcheck_timeout!"10s"} \
            --retries=${hc.healthcheck_retries!"3"} \
  CMD ${hc.healthcheck_cmd!"curl -f http://localhost:8080/health || exit 1"}
</#if>
<#-- ============================================================ -->
<#-- Entrypoint & CMD                                             -->
<#-- ============================================================ -->

<#assign startType = ep.entrypoint_type!"CMD only">
<#assign entrypointExec = ep.entrypoint_cmd!"node">
<#assign cmdArgs = ep.cmd_args!"server.js">
<#if startType == "ENTRYPOINT + CMD">
ENTRYPOINT ["${entrypointExec}"]
CMD ["${cmdArgs}"]
<#elseif startType == "ENTRYPOINT only">
ENTRYPOINT ["${entrypointExec}", "${cmdArgs}"]
<#else>
CMD ["${cmdArgs}"]
</#if>
